version: '3.7'

services:
  db:
    image: postgres:12.2-alpine
    ports:
      - "5431:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    networks:
      - core

  migrate:
    depends_on:
      - db    
    image: peneutron/migrate
    container_name: migrate
    networks:
      - core

  serv:
    depends_on:
      - migrate    
    image: peneutron/sbg
    container_name: serv
    networks:
      - core

networks:
  core:
    driver: bridge

volumes:
  postgres-data: